### ISSUE TITLE
pip install nexusforge not working

### ISSUE THREAD

**Issue by lvsltz** [BlueBrain/nexus-forge#36]
```bash
$ pip install nexusforge

ERROR: Could not find a version that satisfies the requirement nexusforge (from versions: none)
ERROR: No matching distribution found for nexusforge
```

How should nexusforge be installed in a conda environment (python 3.6)

**Comment by MFSY** [comment]
Hi @lvsltz ,

You can use:

`pip install git+https://github.com/BlueBrain/nexus-forge`

We are finalising the .travis setup so that we can publish on PyPi.
You can also try out our notebook examples:

https://mybinder.org/v2/gh/BlueBrain/nexus-forge/master?filepath=examples%2Fnotebooks%2Fgetting-started.

Let us know if this helps.

**Comment by lvsltz** [comment]
Thanks for your quick reply. I'll start with the notebooks on binder, it was not loading before.

**Comment by lvsltz** [comment]
In `BBP KG Search and Download.ipynb` cell's 12 (Run Query), `data` is None
```python
<action> _sparql
<error> QueryingError: 403 Client Error: Forbidden for url: https://bbp.epfl.ch/nexus/v1/views/public/sscx/nxv:defaultSparqlIndex/sparql

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-2c53dc6bceee> in <module>
      8                     limit=limit)
      9 
---> 10 print(str(len(data))+" dataset of type '"+_type+"' found.")

TypeError: object of type 'NoneType' has no len()
```
Then the rest of the cells expectedly don't execute. Can you please fix this?

**Comment by annakristinkaufmann** [comment]
Hi @lvsltz ! The reason was that the type `CellPositions` was not available on the applied context. We have added it now and `data` should no longer be `None`. Additionally, some other issues w.r.t the atlas section of the notebook were fixed on this pull request: https://github.com/BlueBrain/nexus-forge/pull/40

**Comment by lvsltz** [comment]
Actually I am still not able to get past cell 12 in the same notebook, even if I launch the binder image at commit https://github.com/BlueBrain/nexus-forge/commit/f0012f839837e44a513433cc5e85d46ba7f8b6e6 (PR #40).
Here is what I see:
![image](https://user-images.githubusercontent.com/6717189/87414991-d5409080-c5cc-11ea-922b-ed15b5d78c8b.png)

**Comment by MFSY** [comment]
Hi @lvsltz ,

`pip install nexusforge` is now operational. I'll close this ticket. Please reopen it or create an another one if it does not work.
